// <auto-generated />
namespace Council_Tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class YearPhotoURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YearPhotoURL));
        
        string IMigrationMetadata.Id
        {
            get { return "201701032047084_Year&PhotoURL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
